### ISSUE TITLE
Explore feasibility of adding Shibboleth plugin

### ISSUE THREAD

**Issue by moodler** [moodle/moodlenet#40]
Describe  the process in detail of how this could be done now without core changes 

Asking for a site who need this, and just want to give them guidance

**Comment by aleclofabbro** [comment]
that's currently possible by implementing a custom package that would hook to 
- system for user creation, and user messaging/notification if needed
- webapp adding a custom login/signup panel in the access pages

notice that even the current default email-password auhentication system is a plugin de-facto
so that package could be used as a template for other auth systems

**Comment by gthomas2** [comment]
Hi! I'm currently attempting to do this. I have 2+ years node and react experience. Although I can see a lot of thought and hard work has gone into MoodleNet, I have struggled with the available documentation. I've added a forum post about my struggles here: https://moodle.org/mod/forum/discuss.php?d=457807

Any tips would be greatly appreciated.

**Comment by aleclofabbro** [comment]
discussion on this topic is taking place in  https://moodle.org/mod/forum/discuss.php?d=457807
